#!/bin/bash

echo "==> Executing $0"

cd /wordpress/wp-content/plugins/woocommerce-jadlog

DB_EXISTS=$(echo "show databases like '$WORDPRESS_DB_NAME';" | mysql -h $WORDPRESS_DB_HOST -u $WORDPRESS_DB_USER --password=$WORDPRESS_DB_PASSWORD)

echo "==> Installing wordpress tests lib"
SKIP_DB_CREATE=$(test -n "$DB_EXISTS" && echo -n true)
[ "$SKIP_DB_CREATE" ] && echo "==> Database $WORDPRESS_DB_NAME already exists"
WP_TESTS_DIR="/tmp/wordpress-tests-lib" ./bin/install-wp-tests.sh $WORDPRESS_DB_NAME $WORDPRESS_DB_USER $WORDPRESS_DB_PASSWORD $WORDPRESS_DB_HOST latest $SKIP_DB_CREATE

[ $? != 0 ] && echo "==> Install failed. Please, try it again." && exit $?

rsync -rv --exclude=.svn /tmp/wordpress-tests-lib/ $WP_TESTS_DIR/
exit $?

# cd /wordpress && wp scaffold plugin-tests woocommerce-jadlog --ci gitlab --allow-root
